name: RPItems
version: 1.0.0
main: com.scottwoodward.rpitems.RPItems

commands:
   spawnitem:
      description: This is a demo command.
      usage: /spawnitem <ID> <NAME> <LORE>
      permission: rpitems.command.spawnitem
      permission-message: You don't have permission to spawn an item
      
permissions:
  rpitems.command.spawnitem:
    description: Gives access to /spawnitem
    default: op
